name: "Release"

# http://skawashima.com/blog/2019/12/github-actions-auto-release/

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "YYYYMMDD=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Show current datetime
        run: echo ${{ env.YYYYMMDD }}

      - uses: actions/checkout@v3
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: Release/${{ env.YYYYMMDD }}
