name: "Release"

# https://qiita.com/okazy/items/7ab46f2c20ec341a2836
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      # https://qiita.com/itouuuuuuuuu/items/ebf0d4c306b54747374f
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "YYYYMMDD=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
      - name: Show current datetime
        run: echo ${{ env.YYYYMMDD }}

      - uses: actions/checkout@v3
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release/${{ env.YYYYMMDD }}
